---
sudo: required
language: python
services:
  - docker

install:
  # - pip install molecule # Workardound for Molecule/Ansible 2.8 issue
  - pip install docker
  - pip install molecule==2.19 ansible==2.7.11


branches:
  only:
    - master

script:

  # Run tests
  - molecule test --scenario-name=default
  - molecule test --scenario-name=ubuntu_xenial

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
