---

- include: install.freebsd.yml
  when: ansible_distribution == 'FreeBSD'

- include: install.debian.yml
  when: (ansible_distribution == 'Debian') or (ansible_distribution == 'Ubuntu')

- include: install.redhat.yml
  when: (ansible_distribution == 'CentOS') or (ansible_distribution == 'Red Hat Enterprise Linux')
